"""PRD §13's planner as values: the obligation, the ten priorities, the mix, the clock.

Everything in this file is a total function over values — no session, no clock, no provider — for
the same reason `content.lifecycle` is: the questions a planner has to answer out loud ("why is
*this* content next?", "why is it published at 20:00 and not at 23:00?") are answered by a table a
test can enumerate rather than by control flow nobody can replay.

Four properties are load-bearing.

**The planner produces demand, not content.** A `content_obligation` is a queue entry: which
business, which content type, in which window, published when, generated by when. Turning one into
a project is a separate, idempotent step that spends credit — and it is separate precisely so that
a planning mistake costs a row somebody can delete rather than a generation somebody paid for.

**The ten priorities are an order, not a weighted score.** §13.2 numbers them, so `rank_key`
returns a tuple with one component per priority in exactly that order and the comparison is
lexicographic. Each component is a *small discrete bucket* rather than a continuous measure, which
is the only way the later priorities can ever be reached: a deadline compared to the minute would
be almost unique, and priorities 3 through 9 would be unreachable code wearing a specification.

**Two of the ten have a field and no rule, and they say so.** §13.2/4 (past performance) needs
data that is first produced in Phase 5, and §13.2/10 (special days) requires by its own wording a
verified calendar source that has not been chosen. Their rules are constants, their inputs are
carried on `RankContext` and read by nothing, and `UNIMPLEMENTED_PRIORITIES` names them so a test
can assert that setting either input changes no order anywhere.

**The mix is measured, never enforced.** §13.3 is a distribution *target*: `measure_mix` reports
how far each category is from its share, and the only thing that reads the deviation is priority 3,
which reorders. There is no function here that refuses an obligation because of a category's share
— a hard quota would punish exactly the business §13.2/1 says to serve first, the one running a
campaign.

The clock lives here too, because "the business's evening" is arithmetic over a timezone and not a
database question. `planned_publish_at` is meaningful in the tenant's own zone and stored in UTC
(AGENTS.md), so every boundary in this file is computed from a local calendar date and converted
once — never by adding 24 hours to an instant, which is a different thing on the two days a year a
zone changes offset.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, date, datetime, time, timedelta
from enum import IntEnum, StrEnum
from typing import Final
from uuid import UUID
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from app.modules.content.render import RenderProfile, profile_spec
from app.modules.content.script import ScenarioCode

# --- error codes -------------------------------------------------------------------------------
# Every one of these is listed in docs/architecture/error-handling.md. They name why the planner
# refused, never what a tenant's catalogue says.

ERROR_SETTINGS_INVALID: Final = "PLANNER_SETTINGS_INVALID"
ERROR_ITEM_NOT_FOUND: Final = "PLANNER_ITEM_NOT_FOUND"
ERROR_ITEM_INVALID: Final = "PLANNER_ITEM_INVALID"
ERROR_OBLIGATION_NOT_FOUND: Final = "PLANNER_OBLIGATION_NOT_FOUND"
ERROR_OBLIGATION_TRANSITION: Final = "PLANNER_OBLIGATION_TRANSITION_NOT_ALLOWED"
ERROR_TIMEZONE_UNKNOWN: Final = "PLANNER_TIMEZONE_UNKNOWN"
ERROR_QUIET_HOURS_UNRESOLVED: Final = "PLANNER_QUIET_HOURS_UNRESOLVED"

# Recorded on an obligation the planner could not turn into a project because the window closed
# first. Distinct from the codes a refused conversion carries: nothing was refused here, the time
# simply ran out.
REASON_WINDOW_CLOSED: Final = "PLANNER_WINDOW_CLOSED"
# The project this obligation became ended without ever reaching a schedule.
REASON_PROJECT_ENDED: Final = "PLANNER_PROJECT_ENDED"
# The conversion kept failing transiently until the attempt ceiling was reached. The last
# provider-level code is lost on purpose — it is the ceiling that is the fact here.
REASON_ATTEMPTS_EXHAUSTED: Final = "PLANNER_CONVERSION_ATTEMPTS_EXHAUSTED"


class PlannerError(ValueError):
    """A planner refusal expressed as a documented code. Never carries tenant text."""

    def __init__(self, code: str) -> None:
        super().__init__(code)
        self.code = code


# --- the vocabulary ----------------------------------------------------------------------------


class ContentType(StrEnum):
    """§13.1's `content_type`: the publishing surface an obligation is for.

    Closed, and deliberately *not* a second spelling of `RenderProfile`. A profile is a geometry;
    a content type is what a tenant subscribes to ("a Reel a day"), and the mapping below is what
    connects the two. `preview_540x960` has no member here because a review proxy is not a surface
    anybody publishes to — asking for one is something a person does to a project, not something a
    subscription can standingly demand.
    """

    INSTAGRAM_REELS = "instagram_reels"
    INSTAGRAM_STORY = "instagram_story"
    INSTAGRAM_FEED = "instagram_feed"
    INSTAGRAM_SQUARE = "instagram_square"
    X_VIDEO = "x_video"
    X_VERTICAL = "x_vertical"


class ContentCategory(StrEnum):
    """§13.3's weekly mix rows, verbatim and in the section's own order."""

    PRODUCT_SERVICE = "product_service"
    EDUCATIONAL = "educational"
    BRAND_STORY = "brand_story"
    SOCIAL_PROOF = "social_proof"
    ENTERTAINMENT = "entertainment"
    CAMPAIGN = "campaign"
    CORPORATE = "corporate"


class PlanPeriod(StrEnum):
    """How often one standing demand produces an obligation.

    §13.1's example window is a single day. Weekly exists because §13.3's mix is stated per week
    and a "one premium video a week" item (§14.2) is the shape that makes the distribution
    reachable at all. Both boundaries are *local* calendar boundaries — see `period_bounds`.
    """

    DAILY = "daily"
    WEEKLY = "weekly"


class PlanItemStatus(StrEnum):
    """Whether a standing demand is currently producing obligations."""

    ACTIVE = "active"
    PAUSED = "paused"


class ObligationStatus(StrEnum):
    """§13.1's `status`, opened into the states a queue entry actually visits.

    §13.1 shows `planned`. The other five are what happens to a planned thing: it becomes work,
    or it cannot become work and has to say so, or its window closed, or the work it became ended
    one way or the other. `blocked` is the one this slice was asked for by name — an obligation
    that could not be converted must be *visible*, never silently dropped.
    """

    PLANNED = "planned"
    IN_PROGRESS = "in_progress"
    BLOCKED = "blocked"
    FULFILLED = "fulfilled"
    CANCELLED = "cancelled"
    EXPIRED = "expired"


class ObligationEvent(StrEnum):
    """What happened to an obligation, never what to do next (the `lifecycle.py` rule)."""

    CREATED = "created"
    CONVERTED = "converted"
    BLOCKED = "blocked"
    RETRIED = "retried"
    FULFILLED = "fulfilled"
    CANCELLED = "cancelled"
    EXPIRED = "expired"


_TERMINAL_OBLIGATION_STATES: Final[frozenset[ObligationStatus]] = frozenset(
    {ObligationStatus.FULFILLED, ObligationStatus.CANCELLED, ObligationStatus.EXPIRED}
)

_OBLIGATION_TRANSITIONS: Final[
    Mapping[tuple[ObligationStatus, ObligationEvent], ObligationStatus]
] = {
    (ObligationStatus.PLANNED, ObligationEvent.CONVERTED): ObligationStatus.IN_PROGRESS,
    (ObligationStatus.PLANNED, ObligationEvent.BLOCKED): ObligationStatus.BLOCKED,
    # A blocked obligation is not a dead one: the tenant tops up their credit, or the missing
    # product comes back, and the next dispatch pass tries again inside the same window. This
    # edge is why `blocked` is a state rather than a failure code on a cancelled row.
    (ObligationStatus.BLOCKED, ObligationEvent.RETRIED): ObligationStatus.PLANNED,
    (ObligationStatus.BLOCKED, ObligationEvent.CONVERTED): ObligationStatus.IN_PROGRESS,
    (ObligationStatus.IN_PROGRESS, ObligationEvent.FULFILLED): ObligationStatus.FULFILLED,
    # The project ended without reaching a schedule — it failed, or the customer withdrew it.
    # The obligation follows it rather than sitting `in_progress` pointing at a dead project.
    (ObligationStatus.IN_PROGRESS, ObligationEvent.CANCELLED): ObligationStatus.CANCELLED,
    **{
        (status, ObligationEvent.CANCELLED): ObligationStatus.CANCELLED
        for status in (ObligationStatus.PLANNED, ObligationStatus.BLOCKED)
    },
    # Only states that never became work expire. An `in_progress` obligation whose window closed
    # is still producing something the customer will receive, and killing it would throw away a
    # generation that has already been paid for.
    **{
        (status, ObligationEvent.EXPIRED): ObligationStatus.EXPIRED
        for status in (ObligationStatus.PLANNED, ObligationStatus.BLOCKED)
    },
}

INITIAL_OBLIGATION_STATUS: Final = ObligationStatus.PLANNED


def next_obligation_status(
    status: ObligationStatus, event: ObligationEvent
) -> ObligationStatus | None:
    """Where `event` leads from `status`, or `None` when there is no such edge.

    Total over the whole product: the permutation test enumerates every pair and this raises on
    none of them. `None` is a refusal the caller has to handle, never a reason to guess.
    """

    return _OBLIGATION_TRANSITIONS.get((status, event))


def obligation_is_terminal(status: ObligationStatus) -> bool:
    """A status the obligation never leaves: fulfilled, cancelled or expired."""

    return status in _TERMINAL_OBLIGATION_STATES


def obligation_can_cancel(status: ObligationStatus) -> bool:
    """Exactly the non-terminal statuses, derived from the table rather than restated."""

    return next_obligation_status(status, ObligationEvent.CANCELLED) is not None


class ObligationTransitionError(ValueError):
    """A transition the obligation state machine does not draw was attempted."""

    def __init__(self, status: ObligationStatus, event: ObligationEvent) -> None:
        super().__init__(f"{ERROR_OBLIGATION_TRANSITION}: {status.value} -> {event.value}")
        self.code = ERROR_OBLIGATION_TRANSITION
        self.status = status
        self.event = event


def require_obligation_status(status: ObligationStatus, event: ObligationEvent) -> ObligationStatus:
    """`next_obligation_status`, raising rather than returning `None`."""

    target = next_obligation_status(status, event)
    if target is None:
        raise ObligationTransitionError(status, event)
    return target


# --- what a content type is, in the terms the content module already speaks ----------------------

_SURFACES: Final[Mapping[ContentType, tuple[ScenarioCode, RenderProfile]]] = {
    # Only §14.1's daily product reel exists as a scenario, so the content type decides the
    # profile and the scenario is constant. When §14.2's premium video and §14.5's story series
    # arrive, this is the one table that changes; nothing else in the planner knows a profile.
    ContentType.INSTAGRAM_REELS: (
        ScenarioCode.PRODUCT_REELS,
        RenderProfile.INSTAGRAM_REELS_1080X1920,
    ),
    ContentType.INSTAGRAM_STORY: (
        ScenarioCode.PRODUCT_REELS,
        RenderProfile.INSTAGRAM_STORY_1080X1920,
    ),
    ContentType.INSTAGRAM_FEED: (
        ScenarioCode.PRODUCT_REELS,
        RenderProfile.INSTAGRAM_FEED_1080X1350,
    ),
    ContentType.INSTAGRAM_SQUARE: (
        ScenarioCode.PRODUCT_REELS,
        RenderProfile.INSTAGRAM_SQUARE_1080X1080,
    ),
    ContentType.X_VIDEO: (ScenarioCode.PRODUCT_REELS, RenderProfile.X_VIDEO_1280X720),
    ContentType.X_VERTICAL: (ScenarioCode.PRODUCT_REELS, RenderProfile.X_VERTICAL_1080X1920),
}

_UNMAPPED_TYPES = tuple(item.value for item in ContentType if item not in _SURFACES)
if _UNMAPPED_TYPES:  # pragma: no cover - a start-up failure, asserted by the unit suite
    raise RuntimeError(f"content types with no render surface: {_UNMAPPED_TYPES}")


def surface_for(content_type: ContentType) -> tuple[ScenarioCode, RenderProfile]:
    """The scenario and profile a project for this content type is opened with. Total."""

    return _SURFACES[content_type]


class Orientation(StrEnum):
    """How a frame is shaped. Three values, because that is all cropping cares about."""

    PORTRAIT = "portrait"
    LANDSCAPE = "landscape"
    SQUARE = "square"


def orientation_of(width: int, height: int) -> Orientation:
    if width > height:
        return Orientation.LANDSCAPE
    if width < height:
        return Orientation.PORTRAIT
    return Orientation.SQUARE


def target_orientation(profile: RenderProfile) -> Orientation:
    """The shape a profile renders to, read from §19.2's own spec rather than restated."""

    spec = profile_spec(profile)
    return orientation_of(spec.width, spec.height)


# --- the clock ----------------------------------------------------------------------------------


def resolve_timezone(name: str) -> ZoneInfo:
    """The tenant's zone, or a documented refusal. Never a silent fall back to UTC.

    A business row carries a validated IANA name, so this normally cannot fail; it can if the
    host's tz database is older than the name. Defaulting to UTC there would publish a Turkish
    café's evening post at 21:00 local without anybody being told, which is exactly the class of
    silent wrongness `planned_publish_at` exists to prevent.
    """

    try:
        return ZoneInfo(name)
    except (ZoneInfoNotFoundError, ValueError) as error:
        raise PlannerError(ERROR_TIMEZONE_UNKNOWN) from error


@dataclass(frozen=True, slots=True)
class QuietHours:
    """A local window in which nothing is published (§13.2/8).

    Held as minutes past local midnight rather than as a `time` so the wrap-around case has one
    representation: `start == end` means the window is empty, and `start > end` means it crosses
    midnight — which is what a quiet window almost always does.
    """

    start_minute: int
    end_minute: int

    def __post_init__(self) -> None:
        for value in (self.start_minute, self.end_minute):
            if not 0 <= value < _MINUTES_PER_DAY:
                raise PlannerError(ERROR_SETTINGS_INVALID)

    @property
    def is_empty(self) -> bool:
        return self.start_minute == self.end_minute

    def contains(self, moment: time) -> bool:
        """Whether a local wall-clock time falls inside the window. Half-open at the end."""

        if self.is_empty:
            return False
        minute = moment.hour * 60 + moment.minute
        if self.start_minute < self.end_minute:
            return self.start_minute <= minute < self.end_minute
        return minute >= self.start_minute or minute < self.end_minute


_MINUTES_PER_DAY: Final = 24 * 60
# One correction is allowed when a shift lands back inside the window. That can only happen on a
# spring-forward day, where the local time the window ends at does not exist; the offset changes
# by an hour, so one hour is the whole correction. A second failure is a defect, not a date.
_QUIET_HOURS_CORRECTION: Final = timedelta(hours=1)


def local_minute(moment: time) -> int:
    """A wall-clock time as minutes past midnight, the representation `QuietHours` compares in."""

    return moment.hour * 60 + moment.minute


def at_local_time(day: date, minute: int, *, tz: ZoneInfo) -> datetime:
    """The UTC instant of a local wall-clock minute on a local calendar day.

    Built by combining a *date* with a *time* under the zone, never by adding a duration to an
    instant. The two differ by an hour on each transition day, and the difference is the whole
    reason `planned_publish_at` is computed here rather than with arithmetic at a call site.
    """

    wall = datetime.combine(day, time(hour=minute // 60, minute=minute % 60), tzinfo=tz)
    return wall.astimezone(UTC)


def shift_out_of_quiet_hours(
    moment: datetime, *, tz: ZoneInfo, quiet_hours: QuietHours
) -> datetime:
    """Move a publish time out of the quiet window. Never cancels it — §13.2/8 is a shift.

    The moment is pushed to the instant the window ends, in the tenant's own zone. A time that
    was already outside comes back unchanged, which is what makes this safe to apply
    unconditionally.

    The verification afterwards is not defensive noise. On a spring-forward day the local time
    the window ends at may not exist, and the conversion then lands on the offset in force
    *before* the transition — which can put the result back inside the window. One hour is the
    entire size of that error, so one correction resolves it; a second failure means the window
    itself is malformed and is refused rather than looped over.
    """

    if quiet_hours.is_empty:
        return moment
    local = moment.astimezone(tz)
    if not quiet_hours.contains(local.time()):
        return moment
    day = local.date()
    wraps_midnight = quiet_hours.start_minute > quiet_hours.end_minute
    if wraps_midnight and local_minute(local.time()) >= quiet_hours.start_minute:
        # The evening half of a wrapped window: it opened today and closes tomorrow.
        day = day + timedelta(days=1)
    shifted = at_local_time(day, quiet_hours.end_minute, tz=tz)
    if quiet_hours.contains(shifted.astimezone(tz).time()):
        shifted = shifted + _QUIET_HOURS_CORRECTION
    if quiet_hours.contains(shifted.astimezone(tz).time()):
        raise PlannerError(ERROR_QUIET_HOURS_UNRESOLVED)
    return shifted


def period_start_date(day: date, period: PlanPeriod) -> date:
    """The local calendar day a period containing `day` begins on."""

    if period is PlanPeriod.WEEKLY:
        # ISO weeks: Monday. §13.3 states the mix per week and never names a start day, so the
        # calendar's own answer is the one that does not need a setting nobody would ever change.
        return day - timedelta(days=day.weekday())
    return day


def period_length(period: PlanPeriod) -> timedelta:
    return timedelta(days=7 if period is PlanPeriod.WEEKLY else 1)


def period_bounds(day: date, *, period: PlanPeriod, tz: ZoneInfo) -> tuple[datetime, datetime]:
    """The UTC half-open window `[start, end)` of the period containing a local day.

    Both edges are local midnights converted once. A daily window is therefore 23, 24 or 25 hours
    long depending on the date, which is the correct length of a day in a zone that observes DST
    and the reason this is not `start + timedelta(days=1)`.
    """

    start_day = period_start_date(day, period)
    end_day = start_day + period_length(period)
    return (at_local_time(start_day, 0, tz=tz), at_local_time(end_day, 0, tz=tz))


def period_days(*, first: date, period: PlanPeriod, horizon: int) -> tuple[date, ...]:
    """The local start days of every period beginning within `horizon` days of `first`.

    Returned as dates rather than instants because everything downstream — the publish slot, the
    window edges — is built from a local calendar day, and converting early would make the DST
    question reappear at every use.
    """

    if horizon < 0:
        raise PlannerError(ERROR_SETTINGS_INVALID)
    start = period_start_date(first, period)
    step = period_length(period)
    limit = first + timedelta(days=horizon)
    days: list[date] = []
    current = start
    while current <= limit:
        days.append(current)
        current = current + step
    return tuple(days)


@dataclass(frozen=True, slots=True)
class ObligationWindow:
    """One materialised §13.1 obligation's four instants, all UTC, all derived from one zone."""

    period_start: datetime
    period_end: datetime
    planned_publish_at: datetime
    generation_deadline_at: datetime
    # Whether §13.2/8 had to move the publish slot. Recorded rather than inferred: the tenant
    # asked for 23:00, and "why is this at 08:00?" has to be answerable from the row.
    quiet_hours_shifted: bool


def build_window(
    day: date,
    *,
    period: PlanPeriod,
    tz: ZoneInfo,
    publish_minute: int,
    lead_minutes: int,
    quiet_hours: QuietHours,
) -> ObligationWindow:
    """Turn one local period day plus a tenant's preferences into §13.1's four instants.

    `planned_publish_at` may fall outside `[period_start, period_end)` and that is deliberate: a
    quiet window ending after local midnight moves an evening slot into the next day, and the
    honest answer is a post published a few hours late rather than a post not published at all.
    """

    if not 0 <= publish_minute < _MINUTES_PER_DAY or lead_minutes < 0:
        raise PlannerError(ERROR_ITEM_INVALID)
    period_start, period_end = period_bounds(day, period=period, tz=tz)
    requested = at_local_time(day, publish_minute, tz=tz)
    publish_at = shift_out_of_quiet_hours(requested, tz=tz, quiet_hours=quiet_hours)
    return ObligationWindow(
        period_start=period_start,
        period_end=period_end,
        planned_publish_at=publish_at,
        # PRD §13.1 keeps generation strictly before publication, and K5 leans on that: the
        # deadline is what spreads production into the night instead of onto the publish hour.
        generation_deadline_at=publish_at - timedelta(minutes=lead_minutes),
        quiet_hours_shifted=publish_at != requested,
    )


# --- §13.3's mix, measured -----------------------------------------------------------------------

DEFAULT_MIX_SHARES: Final[Mapping[ContentCategory, int]] = {
    ContentCategory.PRODUCT_SERVICE: 25,
    ContentCategory.EDUCATIONAL: 20,
    ContentCategory.BRAND_STORY: 15,
    ContentCategory.SOCIAL_PROOF: 15,
    ContentCategory.ENTERTAINMENT: 10,
    ContentCategory.CAMPAIGN: 10,
    ContentCategory.CORPORATE: 5,
}
"""§13.3's example distribution, transcribed. "Bu oran sektör ve kullanıcı ayarına göre
değişebilir" is why it is a default rather than a constant: a tenant may store its own."""

MIX_TOTAL: Final = 100


@dataclass(frozen=True, slots=True)
class MixTargets:
    """One tenant's target distribution over §13.3's categories.

    Total over `ContentCategory` and summing to 100, both checked here. A distribution with a
    hole in it would silently make one category's deviation unmeasurable, and the whole point of
    measuring is that nobody has to remember which categories were counted.
    """

    shares: Mapping[ContentCategory, int]

    def __post_init__(self) -> None:
        if any(category not in self.shares for category in ContentCategory):
            raise PlannerError(ERROR_SETTINGS_INVALID)
        if len(self.shares) != len(ContentCategory):
            raise PlannerError(ERROR_SETTINGS_INVALID)
        if any(share < 0 for share in self.shares.values()):
            raise PlannerError(ERROR_SETTINGS_INVALID)
        if sum(self.shares.values()) != MIX_TOTAL:
            raise PlannerError(ERROR_SETTINGS_INVALID)

    @classmethod
    def default(cls) -> MixTargets:
        return cls(shares=dict(DEFAULT_MIX_SHARES))

    def as_document(self) -> dict[str, int]:
        """The stored form: category value → share, in §13.3's order."""

        return {category.value: self.shares[category] for category in ContentCategory}

    @classmethod
    def from_document(cls, document: object) -> MixTargets:
        """Read a stored distribution back, refusing anything that is not one."""

        if not isinstance(document, dict):
            raise PlannerError(ERROR_SETTINGS_INVALID)
        shares: dict[ContentCategory, int] = {}
        for category in ContentCategory:
            value = document.get(category.value)
            if not isinstance(value, int) or isinstance(value, bool):
                raise PlannerError(ERROR_SETTINGS_INVALID)
            shares[category] = value
        return cls(shares=shares)


@dataclass(frozen=True, slots=True)
class MixObservation:
    """How far one category is from its share. A measurement, never a verdict."""

    category: ContentCategory
    target_share: int
    actual_share: int
    observed: int
    # Positive means under-served: the target is higher than what was actually produced. Priority
    # 3 reads the sign; nothing reads it as permission to refuse.
    deviation_points: int


def measure_mix(
    targets: MixTargets, counts: Mapping[ContentCategory, int]
) -> tuple[MixObservation, ...]:
    """§13.3's distribution against what actually happened. Pure, total, and never a quota.

    Shares are whole percentage points of the observed total, floor-divided; with nothing
    observed every actual share is zero and every deviation is the target itself, which reads
    correctly as "this business has produced nothing yet, and everything is under-served".

    Returned in §13.3's own category order rather than sorted by deviation. A caller that wants
    the worst offender sorts; a caller rendering a table gets the section's order for free, and a
    stable order is what makes two reports comparable.
    """

    total = sum(max(count, 0) for count in counts.values())
    observations: list[MixObservation] = []
    for category in ContentCategory:
        observed = max(counts.get(category, 0), 0)
        actual = 0 if total == 0 else (observed * MIX_TOTAL) // total
        target = targets.shares[category]
        observations.append(
            MixObservation(
                category=category,
                target_share=target,
                actual_share=actual,
                observed=observed,
                deviation_points=target - actual,
            )
        )
    return tuple(observations)


# --- §13.2's ten priorities ----------------------------------------------------------------------


class PlannerPriority(IntEnum):
    """§13.2's list, numbered as the section numbers it.

    An `IntEnum` because the numbers *are* the specification: the rank key is a tuple in this
    order and the comparison is lexicographic, so priority 1 can never be outweighed by anything
    below it. That is what "saf ve sıralı, ağırlıklı skor değil" means once it is written down.
    """

    ACTIVE_CAMPAIGN = 1
    SUBSCRIPTION_OBLIGATION = 2
    BRAND_CONTENT_BALANCE = 3
    PAST_PERFORMANCE = 4
    MEDIA_SUFFICIENCY = 5
    PRODUCT_REPETITION = 6
    PLATFORM_FORMAT_FIT = 7
    QUIET_HOURS = 8
    USER_PREFERENCE = 9
    SPECIAL_DAYS = 10


UNIMPLEMENTED_PRIORITIES: Final[frozenset[PlannerPriority]] = frozenset(
    {PlannerPriority.PAST_PERFORMANCE, PlannerPriority.SPECIAL_DAYS}
)
"""The two §13.2 entries that have a field and no rule, and why each one does.

**4 — past performance.** The numbers are produced by Phase 5's metrics; there is no column in
this database that holds how a post performed, so a rule here would be ranking on a value nobody
writes. `RankContext.performance_score` exists and is read by nothing.

**10 — special days.** §13.2/10 states its own precondition: "gerçek zamanlı doğrulama
gerekiyorsa web veya doğrulanmış takvim kaynağı". No such source has been chosen, and a
hand-written holiday list would be exactly the invented fact this codebase refuses everywhere
else. `RankContext.special_day_code` exists and is read by nothing.

Both contribute a constant to the rank key, so their positions in §13.2's order are held open
and the sort stays lexicographic over all ten."""


# Bucket codes. Closed, documented, and free of tenant text — they travel to an API response and
# into a log line, which is the whole reason they are constants rather than sentences.
REASON_CAMPAIGN_ACTIVE: Final = "campaign_active"
REASON_CAMPAIGN_ABSENT: Final = "campaign_absent"
REASON_DEADLINE_OVERDUE: Final = "deadline_overdue"
REASON_DEADLINE_IMMINENT: Final = "deadline_imminent"
REASON_DEADLINE_AHEAD: Final = "deadline_ahead"
REASON_MIX_UNDER_TARGET: Final = "mix_under_target"
REASON_MIX_ON_TARGET: Final = "mix_on_target"
REASON_MIX_OVER_TARGET: Final = "mix_over_target"
REASON_PERFORMANCE_NOT_MEASURED: Final = "performance_not_measured"
REASON_MEDIA_SUFFICIENT: Final = "media_sufficient"
REASON_MEDIA_PARTIAL: Final = "media_partial"
REASON_MEDIA_ABSENT: Final = "media_absent"
REASON_PRODUCT_FRESH: Final = "product_not_recently_used"
REASON_PRODUCT_RECENT: Final = "product_used_recently"
REASON_PRODUCT_REPEATED: Final = "product_used_repeatedly"
REASON_FORMAT_NATIVE: Final = "format_native"
REASON_FORMAT_CROPPED: Final = "format_cropped"
REASON_FORMAT_UNKNOWN: Final = "format_unknown"
REASON_SLOT_CLEAR: Final = "slot_outside_quiet_hours"
REASON_SLOT_SHIFTED: Final = "slot_shifted_out_of_quiet_hours"
REASON_PREFERENCE: Final = "tenant_preference_rank"
REASON_SPECIAL_DAYS_NOT_CONFIGURED: Final = "special_days_source_not_configured"


@dataclass(frozen=True, slots=True)
class RankContext:
    """Everything the ten priorities are allowed to look at, for one candidate.

    Read once, by the service, and handed here as values. Nothing in this file queries anything,
    which is what makes "same input, same order" a property rather than a hope.
    """

    obligation_id: UUID
    category: ContentCategory
    planned_publish_at: datetime
    generation_deadline_at: datetime
    # §13.2/1. A campaign the obligation's plan item names, still active in the window.
    has_active_campaign: bool
    # §13.2/3. From `measure_mix`: positive means the category is under its target share.
    mix_deviation_points: int
    # §13.2/5. How many of the named source assets are renderable right now, against how many
    # this deployment considers enough to start.
    renderable_assets: int
    required_assets: int
    # §13.2/6. How many of the tenant's recently delivered projects used the same product.
    recent_product_uses: int
    # §13.2/7. `None` when nothing measurable was found — no renderable asset carries dimensions.
    matches_target_orientation: bool | None
    # §13.2/8. Whether this obligation's slot had to be moved out of the quiet window.
    quiet_hours_shifted: bool
    # §13.2/9. The tenant's own ordering over its standing demands; 0 is highest.
    preference_rank: int
    # §13.2/4 and §13.2/10: carried, never read. See `UNIMPLEMENTED_PRIORITIES`.
    performance_score: int | None = None
    special_day_code: str | None = None


@dataclass(frozen=True, slots=True)
class RankReason:
    """Why one priority put a candidate where it did. One per priority, always all ten."""

    priority: PlannerPriority
    rank: int
    code: str

    def as_document(self) -> dict[str, object]:
        return {"priority": int(self.priority), "rank": self.rank, "code": self.code}


@dataclass(frozen=True, slots=True)
class RankedObligation:
    """One candidate, its position, and the whole derivation of that position."""

    obligation_id: UUID
    position: int
    reasons: tuple[RankReason, ...]

    @property
    def rank_key(self) -> tuple[int, ...]:
        return tuple(reason.rank for reason in self.reasons)


# How much under- or over-service is still "on target". Percentage points, and generous on
# purpose: §13.3 is a distribution over a week, and treating a two-point difference as a
# deviation would make priority 3 reorder on noise.
MIX_TOLERANCE_POINTS: Final = 5


def _rank_campaign(context: RankContext, _now: datetime, _urgent: timedelta) -> RankReason:
    active = context.has_active_campaign
    return RankReason(
        priority=PlannerPriority.ACTIVE_CAMPAIGN,
        rank=0 if active else 1,
        code=REASON_CAMPAIGN_ACTIVE if active else REASON_CAMPAIGN_ABSENT,
    )


def _rank_subscription(context: RankContext, now: datetime, urgent: timedelta) -> RankReason:
    """§13.2/2, bucketed by deadline pressure rather than compared to the minute.

    A raw deadline comparison here would be almost unique per candidate and would make every
    priority below this one unreachable. Three buckets keep ties alive: the commitment that is
    already late, the one that is about to be, and everything else.
    """

    if context.generation_deadline_at <= now:
        return RankReason(PlannerPriority.SUBSCRIPTION_OBLIGATION, 0, REASON_DEADLINE_OVERDUE)
    if context.generation_deadline_at <= now + urgent:
        return RankReason(PlannerPriority.SUBSCRIPTION_OBLIGATION, 1, REASON_DEADLINE_IMMINENT)
    return RankReason(PlannerPriority.SUBSCRIPTION_OBLIGATION, 2, REASON_DEADLINE_AHEAD)


def _rank_balance(context: RankContext, _now: datetime, _urgent: timedelta) -> RankReason:
    """§13.2/3, reading the sign of a measurement and never turning it into a quota."""

    if context.mix_deviation_points > MIX_TOLERANCE_POINTS:
        return RankReason(PlannerPriority.BRAND_CONTENT_BALANCE, 0, REASON_MIX_UNDER_TARGET)
    if context.mix_deviation_points < -MIX_TOLERANCE_POINTS:
        return RankReason(PlannerPriority.BRAND_CONTENT_BALANCE, 2, REASON_MIX_OVER_TARGET)
    return RankReason(PlannerPriority.BRAND_CONTENT_BALANCE, 1, REASON_MIX_ON_TARGET)


def _rank_performance(_context: RankContext, _now: datetime, _urgent: timedelta) -> RankReason:
    """§13.2/4: a field with no rule. Constant, so it never reorders anything."""

    return RankReason(PlannerPriority.PAST_PERFORMANCE, 0, REASON_PERFORMANCE_NOT_MEASURED)


def _rank_media(context: RankContext, _now: datetime, _urgent: timedelta) -> RankReason:
    """§13.2/5. §14.1's fallback is "beklet" rather than "üret kötüsünü", so absent media ranks
    last instead of being refused: the obligation waits inside its window and expires honestly
    if the footage never arrives."""

    if context.renderable_assets <= 0:
        return RankReason(PlannerPriority.MEDIA_SUFFICIENCY, 2, REASON_MEDIA_ABSENT)
    if context.renderable_assets < context.required_assets:
        return RankReason(PlannerPriority.MEDIA_SUFFICIENCY, 1, REASON_MEDIA_PARTIAL)
    return RankReason(PlannerPriority.MEDIA_SUFFICIENCY, 0, REASON_MEDIA_SUFFICIENT)


def _rank_repetition(context: RankContext, _now: datetime, _urgent: timedelta) -> RankReason:
    if context.recent_product_uses <= 0:
        return RankReason(PlannerPriority.PRODUCT_REPETITION, 0, REASON_PRODUCT_FRESH)
    if context.recent_product_uses == 1:
        return RankReason(PlannerPriority.PRODUCT_REPETITION, 1, REASON_PRODUCT_RECENT)
    return RankReason(PlannerPriority.PRODUCT_REPETITION, 2, REASON_PRODUCT_REPEATED)


def _rank_format(context: RankContext, _now: datetime, _urgent: timedelta) -> RankReason:
    """§13.2/7. Not "is this profile supported" — every profile is — but whether the footage is
    the shape the surface wants. Cropped is allowed (`SMART_COVER` exists) and ranks below
    native, because a vertical Reel cut out of a landscape clip loses most of the frame."""

    if context.matches_target_orientation is None:
        return RankReason(PlannerPriority.PLATFORM_FORMAT_FIT, 2, REASON_FORMAT_UNKNOWN)
    if context.matches_target_orientation:
        return RankReason(PlannerPriority.PLATFORM_FORMAT_FIT, 0, REASON_FORMAT_NATIVE)
    return RankReason(PlannerPriority.PLATFORM_FORMAT_FIT, 1, REASON_FORMAT_CROPPED)


def _rank_quiet_hours(context: RankContext, _now: datetime, _urgent: timedelta) -> RankReason:
    """§13.2/8. The window has already been honoured by the time a candidate gets here — the
    slot was shifted when it was built — so what this ranks is whether it *had* to be. A slot the
    tenant actually asked for beats one the planner had to move."""

    shifted = context.quiet_hours_shifted
    return RankReason(
        priority=PlannerPriority.QUIET_HOURS,
        rank=1 if shifted else 0,
        code=REASON_SLOT_SHIFTED if shifted else REASON_SLOT_CLEAR,
    )


def _rank_preference(context: RankContext, _now: datetime, _urgent: timedelta) -> RankReason:
    return RankReason(
        priority=PlannerPriority.USER_PREFERENCE,
        rank=max(context.preference_rank, 0),
        code=REASON_PREFERENCE,
    )


def _rank_special_days(_context: RankContext, _now: datetime, _urgent: timedelta) -> RankReason:
    """§13.2/10: a field with no rule, for the reason the section itself gives."""

    return RankReason(PlannerPriority.SPECIAL_DAYS, 0, REASON_SPECIAL_DAYS_NOT_CONFIGURED)


_PRIORITY_RULES: Final[
    Mapping[PlannerPriority, Callable[[RankContext, datetime, timedelta], RankReason]]
] = {
    PlannerPriority.ACTIVE_CAMPAIGN: _rank_campaign,
    PlannerPriority.SUBSCRIPTION_OBLIGATION: _rank_subscription,
    PlannerPriority.BRAND_CONTENT_BALANCE: _rank_balance,
    PlannerPriority.PAST_PERFORMANCE: _rank_performance,
    PlannerPriority.MEDIA_SUFFICIENCY: _rank_media,
    PlannerPriority.PRODUCT_REPETITION: _rank_repetition,
    PlannerPriority.PLATFORM_FORMAT_FIT: _rank_format,
    PlannerPriority.QUIET_HOURS: _rank_quiet_hours,
    PlannerPriority.USER_PREFERENCE: _rank_preference,
    PlannerPriority.SPECIAL_DAYS: _rank_special_days,
}

_UNRULED = tuple(int(priority) for priority in PlannerPriority if priority not in _PRIORITY_RULES)
if _UNRULED:  # pragma: no cover - a start-up failure, asserted by the unit suite
    raise RuntimeError(f"§13.2 priorities with no rule: {_UNRULED}")


def rank_reasons(
    context: RankContext, *, now: datetime, urgent_window: timedelta
) -> tuple[RankReason, ...]:
    """Every priority's answer for one candidate, in §13.2's order. Total and pure."""

    return tuple(
        _PRIORITY_RULES[priority](context, now, urgent_window) for priority in PlannerPriority
    )


def rank_obligations(
    contexts: Sequence[RankContext], *, now: datetime, urgent_window: timedelta
) -> tuple[RankedObligation, ...]:
    """§13.2's order over a candidate set, with each candidate's derivation attached.

    Deterministic twice over: the key is lexicographic in §13.2's own numbering, and the final
    tie-break is `(planned_publish_at, obligation_id)` so two candidates that every priority
    agrees about still come back in the same order on every run. "Aynı girdi → aynı sıra" is
    therefore a property of the sort rather than of the input's incidental ordering.
    """

    derived = [
        (rank_reasons(context, now=now, urgent_window=urgent_window), context)
        for context in contexts
    ]
    derived.sort(
        key=lambda entry: (
            tuple(reason.rank for reason in entry[0]),
            entry[1].planned_publish_at,
            entry[1].obligation_id,
        )
    )
    return tuple(
        RankedObligation(obligation_id=context.obligation_id, position=index, reasons=reasons)
        for index, (reasons, context) in enumerate(derived)
    )


__all__ = [
    "DEFAULT_MIX_SHARES",
    "ERROR_ITEM_INVALID",
    "ERROR_ITEM_NOT_FOUND",
    "ERROR_OBLIGATION_NOT_FOUND",
    "ERROR_OBLIGATION_TRANSITION",
    "ERROR_QUIET_HOURS_UNRESOLVED",
    "ERROR_SETTINGS_INVALID",
    "ERROR_TIMEZONE_UNKNOWN",
    "INITIAL_OBLIGATION_STATUS",
    "MIX_TOLERANCE_POINTS",
    "MIX_TOTAL",
    "REASON_ATTEMPTS_EXHAUSTED",
    "REASON_PROJECT_ENDED",
    "REASON_WINDOW_CLOSED",
    "UNIMPLEMENTED_PRIORITIES",
    "ContentCategory",
    "ContentType",
    "MixObservation",
    "MixTargets",
    "ObligationEvent",
    "ObligationStatus",
    "ObligationTransitionError",
    "ObligationWindow",
    "Orientation",
    "PlanItemStatus",
    "PlanPeriod",
    "PlannerError",
    "PlannerPriority",
    "QuietHours",
    "RankContext",
    "RankReason",
    "RankedObligation",
    "at_local_time",
    "build_window",
    "local_minute",
    "measure_mix",
    "next_obligation_status",
    "obligation_can_cancel",
    "obligation_is_terminal",
    "orientation_of",
    "period_bounds",
    "period_days",
    "period_length",
    "period_start_date",
    "rank_obligations",
    "rank_reasons",
    "require_obligation_status",
    "resolve_timezone",
    "shift_out_of_quiet_hours",
    "surface_for",
    "target_orientation",
]
